title: "IT Chefs Kitchen üç≥"         
description: "Where Automation Meets Art‚Ñ¢"
url: "https://it-chefs.github.io"
baseurl: "/itchefs-site"
theme: jekyll-theme-cayman
source: docs
markdown: kramdown
highlighter: rouge
encoding: "utf-8"
kramdown:
  input: GFM
  hard_wrap: false
